### PR TITLE
improve header guards

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/uWebSockets/uWebSockets/commit/bc193eb519d314df0d547f190b8cf48ebbd2fd02 "Include guards became longer.").

How do you think about to [append UUIDs there](https://en.wikipedia.org/wiki/Universally_unique_identifier "Description for the usage of  universally unique identifiers")?

**Comment by agauniyal** [comment]
No offence but is @elfring a bot?

**Comment by SEAPUNK** [comment]
Less of a bot, more of a troll, looks like.

**Comment by alexhultman** [comment]
Well, there is some lack of social skill for sure

**Comment by elfring** [comment]
Would you like to inform you  a bit more about my software development activities?

**Comment by SEAPUNK** [comment]
If it involves opening up a [large sum of unhelpful issues](https://i.imgur.com/JBPTPdJ.png), without actually opening up PRs that fix the issue, rather than complaining about it, then no, I think [we all know](https://twitter.com/wesmckinn/status/715690973171306496) what you're doing.

**Comment by elfring** [comment]
Please look again where I contributed something also by the means of pull requests.

**Comment by alexhultman** [comment]
https://en.m.wikipedia.org/wiki/Asperger_syndrome
https://en.m.wikipedia.org/wiki/Narcissism
https://en.m.wikipedia.org/wiki/Napoleon_complex

**Comment by SEAPUNK** [comment]
[Very rare and very infrequent](https://i.imgur.com/wXQkrU0.png), compared to the amount of issues you open?

**Comment by alexhultman** [comment]
Feel free to clean up

**Pull request merged**
