### PR TITLE
Implement uUV api using value/move semantics.

### PR DESCRIPTION
**Pull request by ronag**
This requires more updates but so far I've only updated uUV to discuss the proposal. By using a value/move semantic based interface we should be able to both improve correctness as well as in the future possibly avoid head allocations in favor of copying small data structures.

### CODE REVIEW

**Comment by alexhultman** [comment]
Stop posting these

**Comment by ronag** [comment]
Fair enough. I'll stick with forking.

**Comment by alexhultman** [comment]
Problem is you send a million PRs that you haven't tested, haven't understood the direction to take and in all or many cases change stuff that doesn't matter or simply just introduces more indirection. If you want things merged you need to follow the direction we are heading, test your changes and work on things that are prioritized

**Comment by ronag** [comment]
@alexhultman: No worries! You are right. I'm just getting familiarized with the code and wanted to point out some ideas. I understand if you are busy and don't want to get spammed with random incomplete ideas from random people.

I'm going to play around more with this on my vacation and maybe come with some proper PR:s. Cheers!

**Pull request closed without merging**
