### PR TITLE
add meson build support

### PR DESCRIPTION
**Pull request by agauniyal**
```
mkdir build && cd build
meson ..
ninja
```

make sure to install [meson](https://github.com/mesonbuild/meson), python and ninja on your system.

### CODE REVIEW

**Comment by agauniyal** [comment]
I've managed to build it successfully with meson build system. However I haven't yet replicated full CMake behaviour (installing system/header files) so wait for it.

**Comment by agauniyal** [comment]
Here's the output of meson command - 

```
The Meson build system
Version: 0.33.0
Source dir: /home/agauniyal/projects/uWebSockets
Build dir: /home/agauniyal/projects/uWebSockets/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: µWebSockets
Native cpp compiler: ccache c++ (gcc 6.1.1)
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency zlib found: YES 1.2.8
Native dependency openssl found: YES 1.0.2h
Native dependency libuv found: YES 1.9.1
Build targets in project: 3
```

**Comment by alexhultman** [comment]
Does it build with -O3?

**Comment by agauniyal** [comment]
You mean by default? No, but you can build it with different build options by using `--buildtype` during build. eg. `--buildtype=debugoptimized` or `--buildtype=release`. Or you can use `mesonconf -Dc_args=-Og` for all subsequent builds. So in short, I've left it for user to decide.

**Comment by socmag** [comment]
This sounds pretty good addition tbh.  I just spent two hours ramping up
with meson.  I didn't know about It... seems really sane.  Would like to
try switching over as tooling for our build as well.

On Thu, Aug 25, 2016 at 11:09 AM, Abhinav Gauniyal <notifications@github.com

**Comment by agauniyal** [comment]
Yup and adding uws to your project would be as simple as adding a file with contents -

```
[wrap-git]
directory=uWebSockets
url=https://github.com/uWebSockets/uWebSockets.git
revision=head
```

**Comment by socmag** [comment]
now isn't that pretty :-)

On Thu, Aug 25, 2016 at 11:54 AM, Abhinav Gauniyal <notifications@github.com

**Pull request merged**
