### PR TITLE
add onerror and onopen to complete the standard

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by alexhultman** [comment]
This looks good but you need to process.nextIteration the error callback like it is in the on('error')

**Comment by alexhultman** [comment]
I think so?

**Comment by alexhultman** [comment]
I will take a look at this and see if that is needed. Thanks

**Comment by GusCaplan** [comment]
@alexhultman do you have an estimate for when this might hit npm? we over at [discord.js](https://github.com/hydrabolt/discord.js) are thinking of using this instead of ws

**Pull request merged**
