### PR TITLE
Fix images in npmjs

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
Use full URL to fix image on npmjs website

### CODE REVIEW

**Comment by alexhultman** [comment]
The question I would like to ask is why? Why would NPM suddenly break the images that has been working for a year now. All other project browsers display the images correctly but NPM. I would say this is a bug with NPM itself and they need to fix their broken site.

**Comment by DiegoRBaquero** [comment]
Maybe it works using markdown (?) but using the html version to center did break it?

**Comment by alexhultman** [comment]
I haven't touched any of that in a long time. They just decided to stop fetch images from github.

**Comment by DiegoRBaquero** [comment]
Opened an issue: https://github.com/npm/www/issues/119

**Comment by DiegoRBaquero** [comment]
Either needs to be uncentered or use absolute url for now. 

https://github.com/npm/marky-markdown/issues/320

**Comment by alexhultman** [comment]
well NPM broke it and they should fix it

**Comment by alexhultman** [comment]
thanks for reporting

**Pull request closed without merging**
