### PR TITLE
Fix ws.ping

### LINKED ISSUE #270: ws.ping throws `ReferenceError: send is not defined`
```
node_modules/uws/uws.js:228
        send(message, WebSocketClient.OPCODE_PING);
        ^

ReferenceError: send is not defined
    at WebSocket.ping (node_modules/uws/uws.js:228:9)
```

### PR DESCRIPTION
**Pull request by silverwind**
fixes #270

### CODE REVIEW

**Comment by alexhultman** [comment]
Will this call the correct version of send, depending on what "this" is? As you can see, send differs between WebSocket and WebSocketClient. Will that work, or will the WebSocketClient act as a WebSocket when it calls into ping?

**Comment by SEAPUNK** [comment]
I'm pretty sure it will call `ping` of `WebSocketClient`. So `super.send()` instead?

**Comment by silverwind** [comment]
Hmm, I see that it sends garbage at least (opcode 2). super.send gives 

```
TypeError: (intermediate value).send is not a function
```

**Comment by SEAPUNK** [comment]
Yeah, `super` invokes the extended class's method, but since the method is part of the extended class itself, I'm not sure where `this` plays a part.

**Comment by alexhultman** [comment]
If you look at the stuff I added to the on function it seems logical that "this.send" should call the correct version of send?

**Comment by SEAPUNK** [comment]
Can you try `native.server.send(this.external, message, OPCODE_PING`?

**Comment by silverwind** [comment]
Yep, that works for the server, I see the ping frames. But will it do the correct thing for the client?
```
native.server.send(this.external, message, WebSocketClient.OPCODE_PING);
```

**Comment by SEAPUNK** [comment]
For client, it should be a `pong()` method.

**Comment by alexhultman** [comment]
The client should call native.client.ping

**Comment by silverwind** [comment]
IIRC, both client and server can initate both `ping` and `pong`.

**Comment by alexhultman** [comment]
Pong is not something you send from the application level, that is part of the library and the standard (both server and client automatically respond to pings with a pong).

**Comment by SEAPUNK** [comment]
Yeah. I just misunderstood what silverwind meant by the original comment. I missed that there's both a `native.client` and a `native.server`.

**Comment by silverwind** [comment]
How would I discern a call from a client to one from a server?

**Comment by silverwind** [comment]
Feel free to take over ;)

**Comment by SEAPUNK** [comment]
**OH OH OH**, okay I see what the WebSocketClient class is doing.

So in this case, I'm pretty sure you just create a `ping()` method on the Client class to "shadow" the `WebSocket` class's method, calling `native.client.send`.

**Comment by alexhultman** [comment]
I did test this by printing in the both send() functions and ping() does call the correct send() with this PR applied.

**Comment by alexhultman** [comment]
However, the actual implementation of ping is completely wrong.

**Comment by alexhultman** [comment]
It has to be done like this: 7baccde2616ffcd27388bd22167c4e9b0d42c6ea

**Comment by alexhultman** [comment]
Can you grab the uws.js of master and just overwrite your version and test it. If it works I will push a new version.

**Comment by alexhultman** [comment]
Never mind, it works now. I published a new version.

**Comment by silverwind** [comment]
Looking good from my side:

**Comment by silverwind** [comment]
Btw, I'd be great if you could move `package.json` to the root of the project, so one can install a unreleased version with just `npm install git@github.com:uWebSockets/uWebSockets.git`.

**Comment by alexhultman** [comment]
I'm off to bed, will check on that later. Thanks.

**Pull request merged**
