### PR TITLE
add FD_CLOEXEC after create socket

### PR DESCRIPTION
**Pull request by codehz**
#308 Fixed

### CODE REVIEW

**Comment by alexhultman** [comment]
Could you fix the style and make it wirk on Windows and maybe wrap rhe call to socket. You could have a wrapper called privateSocket that calls socket and sets flags on unix but not on Windows

**Comment by codehz** [comment]
@alexhultman I have fixed it

**Comment by alexhultman** [comment]
We also need to set NO_DELAY so maybe it is better to just have a simple function taking and returning fd while setting all the common default flags.

**Comment by alexhultman** [comment]
Fd = setDefaultFlags(fd)

**Comment by alexhultman** [comment]
Alao - this PR does not follow the style of the project

**Pull request closed without merging**
